//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reshumon.DAL.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentProject { get; set; }
        public int CategoryID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
